apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-deployment
  namespace: ivansanmartin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage-label
  template:
    metadata:
      labels:
        app: homepage-label
    spec:
      containers:
        - name: homepage
          image: homepage:teddy
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          resources:
            limits:
              cpu: 200m
              memory: "64Mi"
            requests:
              cpu: 100m
              memory: "32Mi"

